parser: "babel-eslint"

env:
  browser: true
  es6: true
  node: true

extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'

globals:
  Atomics: readonly
  SharedArrayBuffer: readonly

parserOptions:
  ecmaFeatures:
    jsx: true

  ecmaVersion: 2018
  sourceType: module

plugins:
  - react

rules: {
  "semi": ["warn", "always"],
  "no-multiple-empty-lines": ["warn", {"max": 2}],
  "max-len": ["warn", {
    "code": 85,
    "ignoreComments": false,
    "ignoreTrailingComments": false,
    "ignoreStrings": false,
    "ignoreTemplateLiterals": false
  }],
  "no-unused-vars": ["error", {
    "vars": "all",
    "args": "all",
    "ignoreRestSiblings": true
  }]
}
